import {test,expect,chromium} from '@playwright/test'

test('Rahul shetty login test case',async({page})=>{
    const browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('#login').click()
    await expect(page).toHaveTitle("Let's Shop")
    await browser.close()
    await page.close()
})
test('Rahul shetty logout Link Visibility test case',async({page})=>{
    const browser=await chromium.launch()
    const context=await browser.newContext()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('[value="Login"]').click()
    await expect (page.getByText('Sign Out')).toBeVisible()
    await context.close()
    await browser.close()
    await page.close()

})
test('Rahul shetty logout Link Click test case',async({page})=>{
    const browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('[value="Login"]').click()
    await page.getByText('Sign Out').click()
    await browser.close()
    await page.close()

})
test('Verify Login Success Message Test case',async({page})=>{
    const browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('[value="Login"]').click()
    await expect(page.locator('.toast-container')).toContainText('Login Successfully')
    await browser.close()
    await page.close()

})
test('Verify Logout Success Message Test case',async({page})=>{
    const browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('[value="Login"]').click()
    await page.getByText('Sign Out').click()
    await expect(page.locator('.toast-container')).toContainText('Logout Successfully')
    await browser.close()
    await page.close()

})
test('Check Logo Text Visible or Not',async({page})=>{
    const browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/client/')
    await page.locator('#userEmail').fill('bhushan.trivedi@meetanshi.com')
    await page.locator('#userPassword').fill('Ganesh385')
    await page.locator('[value="Login"]').click()
    await expect(page.getByRole('heading',{name:'Automation1'})).toBeVisible()
    await expect(page.getByText('Automation Practice')).toBeVisible()
    await browser.close()
    await page.close()

})
