import {test,expect, chromium} from '@playwright/test'
test('Navigation method testcase',async({page})=>{
    let browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/AutomationPractice/')
    await page.goto('https://www.google.com')
    await page.goBack()
    await page.goForward()
    browser.close()
    page.close()
})
test("Hidden Elements",async({page})=>{
    let browser=await chromium.launch()
    await page.goto('https://rahulshettyacademy.com/AutomationPractice/')
    await expect(page.locator("#displayed-text")).toBeVisible()
    await page.locator('#hide-textbox').click()
    await expect(page.locator("#displayed-text")).toBeHidden()
    await page.pause()
    await page.on('dialog',dialog=>dialog.accept())
    await page.locator("#confirmbtn").click()
    await expect(page.locator('#mousehover')).toBeVisible()
    await page.locator('#mousehover').hover()
    browser.close()
    page.close()
})
